//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.clans = new HashSet<clan>();
            this.constructions = new HashSet<construction>();
            this.containers = new HashSet<container>();
            this.players = new HashSet<player>();
            this.territories = new HashSet<territory>();
            this.territories1 = new HashSet<territory>();
            this.vehicles = new HashSet<vehicle>();
        }
    
        public string uid { get; set; }
        public Nullable<long> clan_id { get; set; }
        public string name { get; set; }
        public double money { get; set; }
        public int score { get; set; }
        public long kills { get; set; }
        public long deaths { get; set; }
        public long ai_kills { get; set; }
        public long bambi_kills { get; set; }
        public long karma { get; set; }
        public System.DateTime first_connect_at { get; set; }
        public System.DateTime last_connect_at { get; set; }
        public Nullable<System.DateTime> last_disconnect_at { get; set; }
        public long total_connections { get; set; }
    
        public virtual clan clan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clan> clans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<construction> constructions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<container> containers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<player> players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<territory> territories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<territory> territories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicle> vehicles { get; set; }
    }
}
