//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_history
    {
        public long id { get; set; }
        public string account_uid { get; set; }
        public string name { get; set; }
        public System.DateTime died_at { get; set; }
        public double position_x { get; set; }
        public double position_y { get; set; }
        public double position_z { get; set; }
    }
}
