//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class container
    {
        public long id { get; set; }
        public string @class { get; set; }
        public System.DateTime spawned_at { get; set; }
        public string account_uid { get; set; }
        public bool is_locked { get; set; }
        public double position_x { get; set; }
        public double position_y { get; set; }
        public double position_z { get; set; }
        public double direction_x { get; set; }
        public double direction_y { get; set; }
        public double direction_z { get; set; }
        public double up_x { get; set; }
        public double up_y { get; set; }
        public double up_z { get; set; }
        public string cargo_items { get; set; }
        public string cargo_magazines { get; set; }
        public string cargo_weapons { get; set; }
        public string cargo_container { get; set; }
        public string pin_code { get; set; }
        public System.DateTime last_updated_at { get; set; }
        public Nullable<long> territory_id { get; set; }
    
        public virtual account account { get; set; }
        public virtual territory territory { get; set; }
    }
}
