//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public long id { get; set; }
        public string name { get; set; }
        public string account_uid { get; set; }
        public double direction { get; set; }
        public double position_x { get; set; }
        public double position_y { get; set; }
        public double position_z { get; set; }
        public System.DateTime spawned_at { get; set; }
        public string assigned_items { get; set; }
        public string backpack { get; set; }
        public string backpack_items { get; set; }
        public string backpack_magazines { get; set; }
        public string backpack_weapons { get; set; }
        public string current_weapon { get; set; }
        public string goggles { get; set; }
        public string handgun_items { get; set; }
        public string handgun_weapon { get; set; }
        public string headgear { get; set; }
        public string binocular { get; set; }
        public string loaded_magazines { get; set; }
        public string primary_weapon { get; set; }
        public string primary_weapon_items { get; set; }
        public string secondary_weapon { get; set; }
        public string secondary_weapon_items { get; set; }
        public string uniform { get; set; }
        public string uniform_items { get; set; }
        public string uniform_magazines { get; set; }
        public string uniform_weapons { get; set; }
        public string vest { get; set; }
        public string vest_items { get; set; }
        public string vest_magazines { get; set; }
        public string vest_weapons { get; set; }
        public string hitpoints { get; set; }
    
        public virtual account account { get; set; }
    }
}
