//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class territory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public territory()
        {
            this.constructions = new HashSet<construction>();
            this.containers = new HashSet<container>();
        }
    
        public long id { get; set; }
        public string owner_uid { get; set; }
        public string name { get; set; }
        public double position_x { get; set; }
        public double position_y { get; set; }
        public double position_z { get; set; }
        public double radius { get; set; }
        public int level { get; set; }
        public string flag_texture { get; set; }
        public bool flag_stolen { get; set; }
        public string flag_stolen_by_uid { get; set; }
        public Nullable<System.DateTime> flag_stolen_at { get; set; }
        public string flag_steal_message { get; set; }
        public System.DateTime created_at { get; set; }
        public string build_rights { get; set; }
        public string moderators { get; set; }
        public Nullable<System.DateTime> last_paid_at { get; set; }
    
        public virtual account account { get; set; }
        public virtual account account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<construction> constructions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<container> containers { get; set; }
    }
}
